// <auto-generated />
using System;
using FlightRegistration.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightRegistration.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523085410_runaway")]
    partial class runaway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FlightRegistration.Core.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedSeatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSeatId")
                        .IsUnique();

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingTime = new DateTime(2024, 10, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedSeatId = 1,
                            BookingTime = new DateTime(2024, 10, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingTime = new DateTime(2024, 10, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignedSeatId = 5,
                            BookingTime = new DateTime(2024, 10, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookingTime = new DateTime(2024, 10, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookingTime = new DateTime(2024, 10, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 6
                        },
                        new
                        {
                            Id = 7,
                            AssignedSeatId = 21,
                            BookingTime = new DateTime(2024, 10, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookingTime = new DateTime(2024, 10, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookingTime = new DateTime(2024, 10, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 1
                        },
                        new
                        {
                            Id = 10,
                            AssignedSeatId = 41,
                            BookingTime = new DateTime(2024, 10, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookingTime = new DateTime(2024, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 11
                        },
                        new
                        {
                            Id = 12,
                            BookingTime = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 2
                        },
                        new
                        {
                            Id = 13,
                            BookingTime = new DateTime(2024, 10, 1, 19, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 4,
                            PassengerId = 15
                        },
                        new
                        {
                            Id = 14,
                            BookingTime = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 4,
                            PassengerId = 16
                        },
                        new
                        {
                            Id = 15,
                            AssignedSeatId = 81,
                            BookingTime = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 5,
                            PassengerId = 17
                        },
                        new
                        {
                            Id = 16,
                            BookingTime = new DateTime(2024, 10, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 5,
                            PassengerId = 18
                        },
                        new
                        {
                            Id = 17,
                            BookingTime = new DateTime(2024, 10, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 5,
                            PassengerId = 19
                        },
                        new
                        {
                            Id = 18,
                            BookingTime = new DateTime(2024, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 5,
                            PassengerId = 20
                        },
                        new
                        {
                            Id = 19,
                            BookingTime = new DateTime(2024, 10, 1, 21, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 6,
                            PassengerId = 21
                        },
                        new
                        {
                            Id = 20,
                            AssignedSeatId = 108,
                            BookingTime = new DateTime(2024, 10, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 6,
                            PassengerId = 22
                        },
                        new
                        {
                            Id = 21,
                            BookingTime = new DateTime(2024, 10, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 7,
                            PassengerId = 23
                        },
                        new
                        {
                            Id = 22,
                            AssignedSeatId = 124,
                            BookingTime = new DateTime(2024, 10, 2, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 7,
                            PassengerId = 24
                        },
                        new
                        {
                            Id = 23,
                            BookingTime = new DateTime(2024, 10, 4, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 7,
                            PassengerId = 25
                        },
                        new
                        {
                            Id = 24,
                            AssignedSeatId = 131,
                            BookingTime = new DateTime(2024, 10, 5, 22, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 7,
                            PassengerId = 26
                        },
                        new
                        {
                            Id = 25,
                            BookingTime = new DateTime(2024, 10, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 8,
                            PassengerId = 27
                        },
                        new
                        {
                            Id = 26,
                            BookingTime = new DateTime(2024, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 8,
                            PassengerId = 28
                        },
                        new
                        {
                            Id = 27,
                            AssignedSeatId = 162,
                            BookingTime = new DateTime(2024, 10, 4, 2, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 9,
                            PassengerId = 29
                        },
                        new
                        {
                            Id = 28,
                            BookingTime = new DateTime(2024, 10, 5, 21, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 9,
                            PassengerId = 30
                        },
                        new
                        {
                            Id = 29,
                            AssignedSeatId = 181,
                            BookingTime = new DateTime(2024, 10, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 10,
                            PassengerId = 12
                        },
                        new
                        {
                            Id = 30,
                            BookingTime = new DateTime(2024, 10, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 10,
                            PassengerId = 13
                        },
                        new
                        {
                            Id = 31,
                            BookingTime = new DateTime(2024, 10, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 10,
                            PassengerId = 14
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalCity = "FRANKFURT",
                            ArrivalTime = new DateTime(2024, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULAANBAATAR",
                            DepartureTime = new DateTime(2024, 11, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG101",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 2,
                            ArrivalCity = "NEW YORK CITY",
                            ArrivalTime = new DateTime(2024, 11, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "TOKYO",
                            DepartureTime = new DateTime(2024, 11, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG102",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 3,
                            ArrivalCity = "LONDON",
                            ArrivalTime = new DateTime(2024, 11, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "SEOUL",
                            DepartureTime = new DateTime(2024, 11, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG103",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 4,
                            ArrivalCity = "PARIS",
                            ArrivalTime = new DateTime(2024, 11, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "FRANKFURT",
                            DepartureTime = new DateTime(2024, 11, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG104",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 5,
                            ArrivalCity = "SAN FRANCISCO",
                            ArrivalTime = new DateTime(2024, 11, 5, 21, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "NEW YORK CITY",
                            DepartureTime = new DateTime(2024, 11, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG105",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 6,
                            ArrivalCity = "LOS ANGELES",
                            ArrivalTime = new DateTime(2024, 11, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "LONDON",
                            DepartureTime = new DateTime(2024, 11, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG106",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 7,
                            ArrivalCity = "BEIJING",
                            ArrivalTime = new DateTime(2024, 11, 8, 5, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "PARIS",
                            DepartureTime = new DateTime(2024, 11, 7, 21, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG107",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 8,
                            ArrivalCity = "ULAANBAATAR",
                            ArrivalTime = new DateTime(2024, 11, 9, 5, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "SAN FRANCISCO",
                            DepartureTime = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG108",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 9,
                            ArrivalCity = "TOKYO",
                            ArrivalTime = new DateTime(2024, 11, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "LOS ANGELES",
                            DepartureTime = new DateTime(2024, 11, 10, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG109",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 10,
                            ArrivalCity = "SEOUL",
                            ArrivalTime = new DateTime(2024, 11, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "BEIJING",
                            DepartureTime = new DateTime(2024, 11, 11, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG110",
                            Status = 0,
                            TotalSeats = 20
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Nomin",
                            LastName = "Batbold",
                            PassportNumber = "P000001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Temuulen",
                            LastName = "Ganbaatar",
                            PassportNumber = "P000002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Anu",
                            LastName = "Erdene",
                            PassportNumber = "P000003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Khulan",
                            LastName = "Dorj",
                            PassportNumber = "P000004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Chingun",
                            LastName = "Sukhbaatar",
                            PassportNumber = "P000005"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Solongo",
                            LastName = "Purev",
                            PassportNumber = "P000006"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Ankhbayar",
                            LastName = "Ankhiluun",
                            PassportNumber = "P000007"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Maral",
                            LastName = "Tseren",
                            PassportNumber = "P000008"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ganzorig",
                            LastName = "Bold",
                            PassportNumber = "P000009"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Oyundari",
                            LastName = "Munkhbat",
                            PassportNumber = "P000010"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Bat-Erdene",
                            LastName = "Naran",
                            PassportNumber = "P000011"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Ujin",
                            LastName = "Otgon",
                            PassportNumber = "P000012"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Enerel",
                            LastName = "Baatar",
                            PassportNumber = "P000013"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Munkhzul",
                            LastName = "Chimed",
                            PassportNumber = "P000014"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Saruul",
                            LastName = "Jargal",
                            PassportNumber = "P000015"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Tuguldur",
                            LastName = "Altangerel",
                            PassportNumber = "P000016"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Yesugen",
                            LastName = "Zolboo",
                            PassportNumber = "P000017"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Altan",
                            LastName = "Gerel",
                            PassportNumber = "P000018"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Nomin-Erdene",
                            LastName = "Purevdorj",
                            PassportNumber = "P000019"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Emujin",
                            LastName = "Dash",
                            PassportNumber = "P000020"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Odgerel",
                            LastName = "Tuvshin",
                            PassportNumber = "P000021"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Zolzaya",
                            LastName = "Enkhbold",
                            PassportNumber = "P000022"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Batzorig",
                            LastName = "Ganbold",
                            PassportNumber = "P000023"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Delgermaa",
                            LastName = "Demi",
                            PassportNumber = "P000024"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Khongorzul",
                            LastName = "Sainbayar",
                            PassportNumber = "P000025"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Anar",
                            LastName = "Oyun",
                            PassportNumber = "P000026"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Uuriintsolmon",
                            LastName = "Bat-Orgil",
                            PassportNumber = "P000027"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Dulguun",
                            LastName = "Erdenebat",
                            PassportNumber = "P000028"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Batnyam",
                            LastName = "Gantulga",
                            PassportNumber = "P000029"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Bayasgalan",
                            LastName = "Munkh-Erdene",
                            PassportNumber = "P000030"
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsReserved = true,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 2,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 41,
                            FlightId = 3,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 42,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 43,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 44,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 45,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 46,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 47,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 48,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 49,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 50,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 51,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 52,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 53,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 54,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 55,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 56,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 57,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 58,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 59,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 60,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 61,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 62,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 63,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 64,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 65,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 66,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 67,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 68,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 69,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 70,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 71,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 72,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 73,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 74,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 75,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 76,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 77,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 78,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 79,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 80,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 81,
                            FlightId = 5,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 82,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 83,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 84,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 85,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 86,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 87,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 88,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 89,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 90,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 91,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 92,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 93,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 94,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 95,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 96,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 97,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 98,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 99,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 100,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 101,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 102,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 103,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 104,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 105,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 106,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 107,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 108,
                            FlightId = 6,
                            IsReserved = true,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 109,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 110,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 111,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 112,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 113,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 114,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 115,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 116,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 117,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 118,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 119,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 120,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 121,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 122,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 123,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 124,
                            FlightId = 7,
                            IsReserved = true,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 125,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 126,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 127,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 128,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 129,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 130,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 131,
                            FlightId = 7,
                            IsReserved = true,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 132,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 133,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 134,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 135,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 136,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 137,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 138,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 139,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 140,
                            FlightId = 7,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 141,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 142,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 143,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 144,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 145,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 146,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 147,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 148,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 149,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 150,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 151,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 152,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 153,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 154,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 155,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 156,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 157,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 158,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 159,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 160,
                            FlightId = 8,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 161,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 162,
                            FlightId = 9,
                            IsReserved = true,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 163,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 164,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 165,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 166,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 167,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 168,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 169,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 170,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 171,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 172,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 173,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 174,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 175,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 176,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 177,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 178,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 179,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 180,
                            FlightId = 9,
                            IsReserved = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 181,
                            FlightId = 10,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 182,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 183,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 184,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 185,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 186,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 187,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 188,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 189,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 190,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 191,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 192,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 193,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 194,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 195,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 196,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 197,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 198,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 199,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 200,
                            FlightId = 10,
                            IsReserved = false,
                            SeatNumber = "5D"
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Booking", b =>
                {
                    b.HasOne("FlightRegistration.Core.Models.Seat", "AssignedSeat")
                        .WithOne("ReservedByBooking")
                        .HasForeignKey("FlightRegistration.Core.Models.Booking", "AssignedSeatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlightRegistration.Core.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightRegistration.Core.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedSeat");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.HasOne("FlightRegistration.Core.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.Navigation("ReservedByBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
