// <auto-generated />
using System;
using FlightRegistration.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightRegistration.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522181751_MyFreshSeedAttempt")]
    partial class MyFreshSeedAttempt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FlightRegistration.Core.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedSeatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSeatId")
                        .IsUnique();

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingTime = new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedSeatId = 1,
                            BookingTime = new DateTime(2024, 9, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingTime = new DateTime(2024, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 1,
                            PassengerId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingTime = new DateTime(2024, 9, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 4
                        },
                        new
                        {
                            Id = 5,
                            AssignedSeatId = 7,
                            BookingTime = new DateTime(2024, 9, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 2,
                            PassengerId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookingTime = new DateTime(2024, 9, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedSeatId = 11,
                            BookingTime = new DateTime(2024, 9, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 3
                        },
                        new
                        {
                            Id = 8,
                            BookingTime = new DateTime(2024, 9, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            FlightId = 3,
                            PassengerId = 4
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalCity = "TYO",
                            ArrivalTime = new DateTime(2024, 10, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "UBN",
                            DepartureTime = new DateTime(2024, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG101",
                            Status = 0,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 2,
                            ArrivalCity = "UBN",
                            ArrivalTime = new DateTime(2024, 10, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "SEL",
                            DepartureTime = new DateTime(2024, 10, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG202",
                            Status = 0,
                            TotalSeats = 4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalCity = "FRA",
                            ArrivalTime = new DateTime(2024, 10, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "UBN",
                            DepartureTime = new DateTime(2024, 10, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MG303",
                            Status = 0,
                            TotalSeats = 8
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Wonder",
                            PassportNumber = "P000001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Builder",
                            PassportNumber = "P000002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            LastName = "Chaplin",
                            PassportNumber = "P000003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Diana",
                            LastName = "Prince",
                            PassportNumber = "P000004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Edward",
                            LastName = "Elric",
                            PassportNumber = "P000005"
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 2,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 3,
                            IsReserved = true,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2D"
                        });
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Booking", b =>
                {
                    b.HasOne("FlightRegistration.Core.Models.Seat", "AssignedSeat")
                        .WithOne("ReservedByBooking")
                        .HasForeignKey("FlightRegistration.Core.Models.Booking", "AssignedSeatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlightRegistration.Core.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightRegistration.Core.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedSeat");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.HasOne("FlightRegistration.Core.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightRegistration.Core.Models.Seat", b =>
                {
                    b.Navigation("ReservedByBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
